name: overdrive
region: nyc
domains:
  - domain: overdrive.ad
    type: PRIMARY
    zone: overdrive.ad
  - domain: www.overdrive.ad
    type: ALIAS
    zone: overdrive.ad
static_sites:
  - name: overdrive-site
    github:
      repo: neoai2020/overdrive
      branch: main
      deploy_on_push: true
    source_dir: /
    index_document: index.html
    catchall_document: index.html
